"use client";
import { useEffect,useMemo,useState } from "react";
import { io,Socket } from "socket.io-client";

type Mode="HOME"|"LOBBY"|"PLAYER"|"HOST"|"PROJECTOR";
type PrivateTeam={number:number;name:string;cash:number;holdings:Record<string,number>;trades:number;members:{name:string;online:boolean}[]};
const fmt=(c:number)=>new Intl.NumberFormat("vi-VN").format(Math.round(c/100));
const phaseLabel:Record<string,string>={LOBBY:"Phòng chờ",ORIENTATION:"Hướng dẫn",CALM:"Thị trường bình thường",ANNOUNCEMENT:"Công bố biến cố",MARKET_REACTION:"Thị trường phản ứng",POLICY_DECISION:"Quyết định chính sách",POLICY_REACTION:"Phản ứng sau chính sách",RESOLUTION:"Tổng kết chu kỳ",PAUSED:"Tạm dừng",ENDED:"Đóng cửa"};

export default function Home(){
 const [socket,setSocket]=useState<Socket|null>(null),[mode,setMode]=useState<Mode>("HOME"),[room,setRoom]=useState<any>(null),[team,setTeam]=useState<PrivateTeam|null>(null),[online,setOnline]=useState(false),[error,setError]=useState("");
 const [roomCode,setRoomCode]=useState(""),[name,setName]=useState(""),[teamNumber,setTeamNumber]=useState(1),[hostToken,setHostToken]=useState(""),[selected,setSelected]=useState("NOVA"),[qty,setQty]=useState(1),[side,setSide]=useState<"BUY"|"SELL">("BUY"),[now,setNow]=useState(Date.now());
 useEffect(()=>{const s=io({transports:["websocket","polling"]});setSocket(s);s.on("connect",()=>setOnline(true));s.on("disconnect",()=>setOnline(false));s.on("room:state",setRoom);s.on("team:private",setTeam);const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{s.close();clearInterval(timer)}},[]);
 const remaining=Math.max(0,Math.ceil(((room?.phaseEndsAt||now)-now)/1000));
 const stock=room?.stocks?.find((s:any)=>s.symbol===selected);const price=room?.prices?.[selected]||0;
 const netWorth=team?team.cash+Object.entries(team.holdings).reduce((n,[s,q])=>n+(room?.prices?.[s]||0)*(q as number),0):0;
 const currentEvent=room?.events?.find((e:any)=>e.id===room.activeEventId),currentPolicy=room?.policies?.find((p:any)=>p.id===room.activePolicyId);
 const policyOptions=room?.policies?.filter((p:any)=>currentEvent?.responsePolicyIds?.includes(p.id))||[];
 const leaderboard=useMemo(()=>room?.teams?[...room.teams].map((t:any)=>({name:t.name,online:t.members.filter((m:any)=>m.online).length})):[],[room]);
 function ack(event:string,data:any,success?:(r:any)=>void){setError("");socket?.emit(event,data,(r:any)=>{if(!r?.ok)setError(r?.error||"Không thể thực hiện.");else success?.(r)})}
 function createRoom(){ack("host:create",{hostName:name||"Host nhóm 7",startingCash:10000000},r=>{setRoomCode(r.roomCode);setHostToken(r.hostToken);sessionStorage.setItem("host",JSON.stringify(r));setMode("HOST")})}
 function join(){ack("player:join",{roomCode,name,teamNumber},()=>setMode("PLAYER"))}
 function hostCmd(command:string,value?:string){ack("host:command",{command,value})}
 function trade(){ack("trade:execute",{symbol:selected,side,quantity:qty,key:crypto.randomUUID()},()=>setError("Lệnh đã khớp thành công."))}
 function vote(policyId:string){ack("policy:vote",{policyId},()=>setError("Đã ghi nhận phiếu của đội."))}
 if(mode==="HOME")return <main className="landing"><header><Brand/><span className={online?"status on":"status"}>{online?"Server sẵn sàng":"Đang kết nối"}</span></header><section className="landing-grid"><div className="intro"><p className="kicker">MÔ PHỎNG KINH TẾ REALTIME</p><h1>Thị trường tạo động lực.<br/><em>Chính sách tạo hướng đi.</em></h1><p>8 đội cùng giao dịch, phản ứng trước biến cố và lựa chọn chính sách. Lợi nhuận cao nhất chưa chắc là phát triển tốt nhất.</p><div className="pill-row"><span>8 doanh nghiệp</span><span>Event–Policy Cycle</span><span>20+ thiết bị</span></div></div><div className="join-card"><h2>Vào MarketLab</h2><label>TÊN HIỂN THỊ<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ví dụ: Minh Anh"/></label><label>MÃ PHÒNG<input value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())} placeholder="ABCD" maxLength={4}/></label><label>CHỌN NHÓM<select value={teamNumber} onChange={e=>setTeamNumber(Number(e.target.value))}>{[1,2,3,4,5,6,8,9].map(n=><option key={n} value={n}>Nhóm {n}</option>)}</select></label><button className="cta" disabled={!name||roomCode.length<4} onClick={join}>Tham gia phòng</button><div className="divider">DÀNH CHO NHÓM TỔ CHỨC</div><button className="secondary" onClick={createRoom}>Tạo phòng mới</button>{error&&<p className="error">{error}</p>}</div></section><footer>Game giáo dục · Không phải lời khuyên đầu tư</footer></main>;
 if(!room)return <main className="center"><div className="loader"/><p>Đang đồng bộ phòng…</p></main>;
 if(mode==="HOST")return <main className="terminal"><Top room={room} remaining={remaining} online={online}/><section className="host-layout"><div><section className="hero-panel"><p className="kicker">HOST DASHBOARD · ROOM {room.code}</p><h1>{phaseLabel[room.phase]}</h1><p>{currentEvent?.title||"Sẵn sàng đưa lớp vào thị trường"}</p><div className="host-buttons"><button onClick={()=>hostCmd("START")} disabled={room.phase!=="LOBBY"}>Bắt đầu</button><button onClick={()=>hostCmd(room.phase==="PAUSED"?"RESUME":"PAUSE")}>{room.phase==="PAUSED"?"Tiếp tục":"Tạm dừng"}</button><button onClick={()=>hostCmd("NEXT")}>Chuyển phase</button><button onClick={()=>hostCmd("BOT")}>Thêm bot</button><button className="danger" onClick={()=>hostCmd("END")}>Emergency freeze</button></div></section><MarketBoard room={room} selected={selected} setSelected={setSelected}/><EventPanel event={currentEvent} policy={currentPolicy}/></div><aside><section className="side-card"><h3>Đội trong phòng</h3>{leaderboard.map((t:any)=><div className="team-line" key={t.name}><span>{t.name}</span><b className={t.online?"green":""}>{t.online}/2 online</b></div>)}</section><section className="side-card"><h3>Chỉ số quốc gia</h3>{Object.entries(room.indicators).map(([k,v])=><Meter key={k} label={k} value={v as number}/>)}</section>{room.phase==="POLICY_DECISION"&&<section className="side-card"><h3>Chọn chính sách</h3>{policyOptions.map((p:any)=><button className="policy" key={p.id} onClick={()=>hostCmd("APPLY_POLICY",p.id)}><b>{p.title}</b><small>{p.description}</small></button>)}</section>}<section className="side-card logs"><h3>Nhật ký</h3>{room.logs.slice(0,8).map((l:any,i:number)=><p key={i}>{l.text}</p>)}</section></aside></section>{error&&<Toast text={error}/>}</main>;
 return <main className="terminal"><Top room={room} remaining={remaining} online={online}/><section className="player-head"><div><p className="kicker">{currentEvent?.category||"MARKETLAB LIVE"}</p><h1>{currentEvent?.title||phaseLabel[room.phase]}</h1><p>{currentEvent?.description||"Theo dõi thị trường và chuẩn bị chiến lược."}</p></div><div className="wallet"><span>{team?.name||`Nhóm ${teamNumber}`}</span><small>TỔNG TÀI SẢN</small><b>{fmt(netWorth)} ML$</b><em>Tiền mặt {fmt(team?.cash||0)} ML$</em></div></section><section className="trade-layout"><div><MarketBoard room={room} selected={selected} setSelected={setSelected}/><EventPanel event={currentEvent} policy={currentPolicy}/>{room.phase==="POLICY_DECISION"&&<section className="vote-panel"><p className="kicker">MỖI ĐỘI MỘT PHIẾU</p><h2>Chọn phản ứng chính sách</h2><div>{policyOptions.map((p:any)=><button key={p.id} onClick={()=>vote(p.id)}><b>{p.title}</b><small>{p.description}</small></button>)}</div></section>}</div><aside className="order-card"><div className="tabs"><button className={side==="BUY"?"active buy":""} onClick={()=>setSide("BUY")}>MUA</button><button className={side==="SELL"?"active sell":""} onClick={()=>setSide("SELL")}>BÁN</button></div><h2>{selected}</h2><p>{stock?.name}</p><strong className="live-price">{fmt(price)} ML$</strong><label>SỐ LƯỢNG<input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)))}/></label><div className="quick">{[.25,.5,.75,1].map(x=><button key={x} onClick={()=>setQty(side==="BUY"?Math.max(1,Math.floor((team?.cash||0)*x/price)):Math.max(1,Math.floor((team?.holdings?.[selected]||0)*x)))}>{x===1?"ALL":`${x*100}%`}</button>)}</div><div className="summary"><span>Tạm tính</span><b>{fmt(price*qty)} ML$</b><span>Phí 0,15%</span><b>{fmt(price*qty*.0015)} ML$</b></div><button className={side==="BUY"?"execute buy":"execute sell"} disabled={!['CALM','MARKET_REACTION','POLICY_REACTION'].includes(room.phase)} onClick={trade}>{side==="BUY"?"Xác nhận mua":"Xác nhận bán"}</button><p className="fine">Đang giữ: {team?.holdings?.[selected]||0} cổ phiếu</p><hr/><h3>Danh mục</h3>{Object.entries(team?.holdings||{}).filter(([,q])=>(q as number)>0).map(([s,q])=><div className="holding" key={s}><span>{s} × {q as number}</span><b>{fmt((room.prices[s]||0)*(q as number))}</b></div>)}</aside></section>{error&&<Toast text={error}/>}</main>;
}

function Brand(){return <div className="brand"><i>M</i><b>MARKETLAB</b><span>2035</span></div>}
function Top({room,remaining,online}:{room:any;remaining:number;online:boolean}){return <header className="top"><Brand/><div className="phase"><span>{phaseLabel[room.phase]}</span><b>{String(Math.floor(remaining/60)).padStart(2,"0")}:{String(remaining%60).padStart(2,"0")}</b></div><div className={online?"connection on":"connection"}>{online?"LIVE":"OFFLINE"}</div></header>}
function MarketBoard({room,selected,setSelected}:{room:any;selected:string;setSelected:(s:string)=>void}){return <section className="market-board"><div className="chart"><div className="chart-title"><div><b>{selected}</b><span>{room.stocks.find((s:any)=>s.symbol===selected)?.name}</span></div><strong>{fmt(room.prices[selected])} ML$</strong></div><PriceChart values={(room.history[selected]||[]).map((x:any)=>x.price).concat(room.prices[selected])}/></div><div className="watch"><div className="watch-title">THỊ TRƯỜNG</div>{room.stocks.map((s:any)=>{const change=(room.prices[s.symbol]/room.openPrices[s.symbol]-1)*100;return <button className={selected===s.symbol?"selected":""} key={s.symbol} onClick={()=>setSelected(s.symbol)}><i style={{background:s.color}}/><div><b>{s.symbol}</b><small>{s.sector}</small></div><span><b>{fmt(room.prices[s.symbol])}</b><small className={change>=0?"up":"down"}>{change>=0?"+":""}{change.toFixed(1)}%</small></span></button>})}</div></section>}
function PriceChart({values}:{values:number[]}){const a=values.length<2?[values[0]||0,values[0]||0]:values,min=Math.min(...a),max=Math.max(...a),pts=a.map((v,i)=>`${i/(a.length-1)*800},${220-(v-min)/(max-min||1)*180}`).join(" ");return <svg viewBox="0 0 800 250" className="price-chart"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#a3e635" stopOpacity=".32"/><stop offset="1" stopColor="#a3e635" stopOpacity="0"/></linearGradient></defs><polyline points={`${pts} 800,250 0,250`} fill="url(#area)" stroke="none"/><polyline points={pts} fill="none" stroke="#a3e635" strokeWidth="3"/></svg>}
function EventPanel({event,policy}:{event:any;policy:any}){if(!event&&!policy)return null;return <section className="event-panel"><div><span>BIẾN CỐ</span><b>{event?.title}</b><p>{event?.lesson}</p></div>{policy&&<div><span>CHÍNH SÁCH ĐANG ÁP DỤNG</span><b>{policy.title}</b><p>{policy.lesson}</p></div>}</section>}
function Meter({label,value}:{label:string;value:number}){return <div className="meter"><span>{label}</span><div><i style={{width:`${value}%`}}/></div><b>{Math.round(value)}</b></div>}
function Toast({text}:{text:string}){return <div className="toast">{text}</div>}
